# Generated by Django 2.1.2 on 2018-11-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOfApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('length', models.IntegerField()),
                ('level', models.CharField(choices=[('poczatkujacy', 'poczatkujacy'), ('srednio_zaawansowany', 'srednio_zaawansowany'), ('zaawansowany', 'zaawansowany')], default='poczatkujacy', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CategoryOfCourse')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressInCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualTime', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CourseOfApp')),
            ],
        ),
        migrations.CreateModel(
            name='TagOfCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserOfApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('nickname', models.CharField(max_length=60, unique=True)),
                ('courses', models.ManyToManyField(blank=True, null=True, to='app.CourseOfApp')),
            ],
        ),
        migrations.AddField(
            model_name='progressincourse',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserOfApp'),
        ),
        migrations.AddField(
            model_name='courseofapp',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.TagOfCourse'),
        ),
    ]
